<?xml version="1.0" encoding="utf-8"?><Database Name="Accountancy" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-KCQ4LOO\SQLEXPRESS01;Initial Catalog=Accountancy;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AccountancyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FinancialElementType" Member="FinancialElementTypes">
    <Type Name="FinancialElementType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FinancialElementType_JournalEntry" Member="JournalEntries" ThisKey="Id" OtherKey="ElementTypeId" Type="JournalEntry" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoginId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegisteredOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_GeneralJournalEntry" Member="GeneralJournalEntries" ThisKey="Id" OtherKey="UserId" Type="GeneralJournalEntry" />
    </Type>
  </Table>
  <Table Name="dbo.JournalEntries" Member="JournalEntries">
    <Type Name="JournalEntry">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JournalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElementTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FinancialElementType_JournalEntry" Member="FinancialElementType" ThisKey="ElementTypeId" OtherKey="Id" Type="FinancialElementType" IsForeignKey="true" />
      <Association Name="Transactiontype_JournalEntry" Member="Transactiontype" ThisKey="TransactionTypeId" OtherKey="Id" Type="Transactiontype" IsForeignKey="true" />
      <Association Name="GeneralJournalEntry_JournalEntry" Member="GeneralJournalEntry" ThisKey="JournalId" OtherKey="Id" Type="GeneralJournalEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactiontype" Member="Transactiontypes">
    <Type Name="Transactiontype">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Transactiontype_JournalEntry" Member="JournalEntries" ThisKey="Id" OtherKey="TransactionTypeId" Type="JournalEntry" />
    </Type>
  </Table>
  <Table Name="dbo.GeneralJournalEntries" Member="GeneralJournalEntries">
    <Type Name="GeneralJournalEntry">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="GeneralJournalEntry_JournalEntry" Member="JournalEntries" ThisKey="Id" OtherKey="JournalId" Type="JournalEntry" />
      <Association Name="User_GeneralJournalEntry" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>